repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        exclude: ^Charts/|/templates/
      - id: check-merge-conflict
      # - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: tech-ui
        name: generate and validate the synoptic and component screens
        language: system
        # only do this if the techui support submodule has been added
        entry: |
          bash -c "
            if [[ -f synoptic/techui-support/techui-support.yaml ]]; then
              uvx techui-builder synoptic/techui.yaml
            fi"
        files: ^synoptic/
        pass_filenames: false

  - repo: local
    hooks:
      - id: ibek-runtime-schema
        name: generate schema for local ibek entities
        language: system
        # only do this if there are ibek runtime support files present
        entry: |
          bash -c "
            support=$(find ibek-runtime-support/ -name '*.ibek.support.yaml')
            if [[ -n ${support} ]]; then
              uvx ibek ioc generate-schema ${support} \
                --output ibek-runtime-support/runtime.schema.json
            fi"
        files: ^ibek-runtime-support/
        pass_filenames: false
