# yaml-language-server: $schema=../../.helm-shared/values.schema.json

ioc-instance:
  image: ghcr.io/epics-containers/ioc-adsimdetector-runtime:2025.8.2

  # mount in the beamline data folder
  # dataVolume:
  #   pvc: false
  #   hostPath: /dls/ixx/data
